import './global.css';

export const metadata = {
  title: 'Welcome to photo-booth',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"bg-blue-300"}>{children}</body>
    </html>
  );
}
